### PR TITLE
feat: bright colors variants

### PR DESCRIPTION
**Pull request by MHase**
Bright colors variants as mentioned in #47 😄 
Also added few empty lines separating colors group for easier navigating through the code

### CODE REVIEW

**Comment by MrFoxPro** [comment]
Is it possible to add orange color?

**Comment by MHase** [comment]
@MrFoxPro absolutely I can contribute to that :) but this PR focus only on adding corresponding/existing colors in bright variants. if that will/would be accepted then I can proceed in adding something more 👍🏻

**Comment by WaldoJeffers** [comment]
Thanks for your work @MHase 
Any chance of seeing this merged? 
I feel it would really help people who are migrating from chalk -> picocolors

Or are there any issues with the PR, or the impact it would have on the overall size?

**Comment by MHase** [comment]
@WaldoJeffers I would love to see this merged, but we need someone to approve/merge this PR for us
```Only those with write access to this repository can merge pull requests.```

Any idea who we can ping to move this forward?

**Comment by MrFoxPro** [comment]
@alexeyraspopov

**Comment by jaclas** [comment]
Still not approved? What is it about? I also need "bright" colors.
@marco-carvalho @borodean @alexeyraspopov ?

**Comment by MHase** [comment]
based on responses it looks like this repo was abandoned...

**Comment by jaclas** [comment]
15 million projects use this module, maybe someone will take it further...

**Comment by alexeyraspopov** [comment]
The library is mostly used indirectly, by other more significant projects. I appreciate the PRs and will get back to them as soon as I got time, but I can’t just prioritize PRs that start bloating the size for little to no benefit.

Thanks

**Comment by jaclas** [comment]
@alexeyraspopov Thanks for showing up!
This PR increases the size by just a few hundred bytes, in return doubles the number of available colors. And most importantly, it fulfills the promise of easy migration from Chalk, where *Bright colors are present.

**Comment by 43081j** [comment]
@alexeyraspopov any chance we can get these bright colours over the line? 

As part of the ecosystem cleanup effort I'm leading, we're replacing chalk & others with picocolours in many popular repos. The only missing thing that all other alternatives have seems to be these variants

If you need any help maintaining this too, let me know. I would be happy to help, especially given I'm making quite a few large packages depend on it

**Comment by 43081j** [comment]
@MHase can you possibly catch this up from main? The fallback logic was refactored since, so there's probably some conflicts

**Comment by WuglyakBolgoink** [comment]
Hallo @MHase / @alexeyraspopov  !

but this PR was not published on npm? correct?

**Comment by MHase** [comment]
@WuglyakBolgoink unfortunately correct
the latest release was on 14 May with version `1.0.1`

**Comment by trivikr** [comment]
@alexeyraspopov When is this expected to be published?
Is it going to be in `1.1.0` or `1.0.2`?

**Comment by alexeyraspopov** [comment]
I will publish `1.1.0` once https://github.com/alexeyraspopov/picocolors/pull/71 is resolved

**Comment by trivikr** [comment]
@alexeyraspopov Can you publish `1.0.2` with this fix in the meantime to unblock migrations from chalk?

---

I just posted a PR to migrate from `chalk` to `picocolors` in changesets https://github.com/changesets/changesets/pull/1417
The maintainers have not reviewed it at the time of comment, but there's a possibility they might block it because of the absence of `redBright` API.

I also posted migrations requests on popular repos, where maintainers seem to be onboard at the time of comment:
* jest https://github.com/jestjs/jest/issues/15189
* eslint https://github.com/eslint/eslint/issues/18686

**Comment by kravetsone** [comment]
> I will publish `1.1.0` once #71 is resolved

we need this( please publish it in `1.0.2`

**Pull request merged**
